on: create

name: Release
jobs:
  release:
    name: Release GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/release-github-actions@9580048dfe815fe6024e10d25a277efc5e154eed # v8.0.2